nodeLinker: isolated
shamefullyHoist: false
autoInstallPeers: true
strictPeerDependencies: false
overrides:
  jws: 4.0.1
  "@modelcontextprotocol/sdk": ^1.24.3
allowBuilds:
  '@sentry/cli': set this to true or false
  bcrypt: set this to true or false
  core-js: set this to true or false
  esbuild: set this to true or false
  msw: set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
