import type { RedditGapResults } from './types'

export interface RedditGapEmailInput {
  email: string
  results: RedditGapResults
  auditId?: string
}

export interface RedditGapEmailPayload {
  to: string
  subject: string
  text: string
  html?: string
}

function getReportUrl(auditId?: string): string {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000'
  return auditId ? `${baseUrl}/reddit-gap/results/${auditId}` : baseUrl
}

export function buildRedditGapEmailPayload(input: RedditGapEmailInput): RedditGapEmailPayload {
  const reportUrl = getReportUrl(input.auditId)
  const { results } = input

  const subject = `Reddit Content Gap Analysis: ${results.topic}`
  
  const text = [
    `Your Reddit Content Gap Analysis for "${results.topic}" is ready.`,
    ``,
    `📊 ANALYSIS SUMMARY`,
    `==================`,
    `Topic: ${results.topic}`,
    `Subreddits Analyzed: ${results.discoveredSubreddits.length}`,
    `Threads Analyzed: ${results.analyzedThreads}`,
    `Content Gaps Found: ${results.contentGaps.length}`,
    `Total Questions: ${results.totalQuestionsFound}`,
    `Analysis Confidence: ${results.analysisConfidence}%`,
    ``,
    `🎯 TOP CONTENT GAP`,
    `==================`,
    results.topGapPreview 
      ? `${results.topGapPreview.question}`
      : 'No clear content gap identified',
    ``,
    results.topGapPreview?.context 
      ? `Context: ${results.topGapPreview.context}`
      : '',
    ``,
    `📈 OPPORTUNITY SCORECARD`,
    `========================`,
    `Overall Gap Score: ${results.scorecard.overallGapScore}/100`,
    `Opportunity Score: ${results.scorecard.opportunityScore}/100`,
    `Engagement Density: ${results.scorecard.engagementDensity}/100`,
    `Question Coverage: ${results.scorecard.questionCoverage}/100`,
    `Competitive Advantage: ${results.scorecard.competitiveAdvantage}/100`,
    ``,
    `🚀 MOMENTUM: ${results.scorecard.momentumCategory.label}`,
    `${results.scorecard.momentumCategory.summary}`,
    ``,
    `📋 BENCHMARK: ${results.scorecard.benchmarkBand.label}`,
    `${results.scorecard.benchmarkBand.summary}`,
    ``,
    `💡 KEY STRENGTHS`,
    `================`,
    ...results.scorecard.strengths.map(s => `• ${s.title}: ${s.detail}`),
    ``,
    `🎯 TOP 3 OPPORTUNITIES`,
    `=====================`,
    ...results.scorecard.opportunities.slice(0, 3).map((opp, i) => 
      `${i + 1}. ${opp.title}\n   ${opp.detail}\n   Action: ${opp.action}\n   Effort: ${opp.effort} | Timeframe: ${opp.timeframe}`
    ),
    ``,
    `⚡ FASTEST WIN`,
    `===============`,
    `${results.scorecard.fastestWin.title}`,
    `${results.scorecard.fastestWin.detail}`,
    `Action: ${results.scorecard.fastestWin.action}`,
    `Expected Lift: ${results.scorecard.fastestWin.expectedLift}`,
    ``,
    `🔥 BIGGEST OPPORTUNITY`,
    `======================`,
    `${results.scorecard.biggestOpportunity.title}`,
    `${results.scorecard.biggestOpportunity.detail}`,
    `Action: ${results.scorecard.biggestOpportunity.action}`,
    `Expected Lift: ${results.scorecard.biggestOpportunity.expectedLift}`,
    ``,
    `📅 ACTION PLAN`,
    `===============`,
    `Next 7 Days:`,
    ...results.scorecard.actionPlan.next7Days.map(item => `• ${item}`),
    ``,
    `Next 30 Days:`,
    ...results.scorecard.actionPlan.next30Days.map(item => `• ${item}`),
    ``,
    `Next 90 Days:`,
    ...results.scorecard.actionPlan.next90Days.map(item => `• ${item}`),
    ``,
    `🔗 VIEW FULL REPORT`,
    `==================`,
    `${reportUrl}`,
    ``,
    `---`,
    `Generated by FlowIntent Reddit Gap Analysis`,
    `AI-powered content strategy insights from Reddit discussions`
  ].filter(Boolean).join('\n')

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Reddit Content Gap Analysis</title>
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 10px; text-align: center; margin-bottom: 30px; }
        .section { background: #f8f9fa; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
        .metric { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #e9ecef; }
        .metric:last-child { border-bottom: none; }
        .highlight { background: #fff3cd; padding: 15px; border-radius: 8px; border-left: 4px solid #ffc107; margin: 20px 0; }
        .opportunity { background: #d1ecf1; padding: 15px; border-radius: 8px; border-left: 4px solid #17a2b8; margin: 10px 0; }
        .cta { background: #28a745; color: white; padding: 15px 30px; text-decoration: none; border-radius: 5px; display: inline-block; margin: 20px 0; }
        .footer { text-align: center; color: #6c757d; font-size: 14px; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e9ecef; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>📊 Reddit Content Gap Analysis</h1>
        <h2>${results.topic}</h2>
        <p>AI-powered insights from Reddit discussions</p>
      </div>

      <div class="section">
        <h3>📈 Analysis Summary</h3>
        <div class="metric">
          <span>Subreddits Analyzed</span>
          <strong>${results.discoveredSubreddits.length}</strong>
        </div>
        <div class="metric">
          <span>Threads Analyzed</span>
          <strong>${results.analyzedThreads}</strong>
        </div>
        <div class="metric">
          <span>Content Gaps Found</span>
          <strong>${results.contentGaps.length}</strong>
        </div>
        <div class="metric">
          <span>Analysis Confidence</span>
          <strong>${results.analysisConfidence}%</strong>
        </div>
      </div>

      ${results.topGapPreview ? `
      <div class="highlight">
        <h3>🎯 Top Content Gap</h3>
        <p><strong>${results.topGapPreview.question}</strong></p>
        <p>${results.topGapPreview.context}</p>
      </div>
      ` : ''}

      <div class="section">
        <h3>📊 Opportunity Scorecard</h3>
        <div class="metric">
          <span>Overall Gap Score</span>
          <strong>${results.scorecard.overallGapScore}/100</strong>
        </div>
        <div class="metric">
          <span>Opportunity Score</span>
          <strong>${results.scorecard.opportunityScore}/100</strong>
        </div>
        <div class="metric">
          <span>Engagement Density</span>
          <strong>${results.scorecard.engagementDensity}/100</strong>
        </div>
        <div class="metric">
          <span>Competitive Advantage</span>
          <strong>${results.scorecard.competitiveAdvantage}/100</strong>
        </div>
      </div>

      <div class="section">
        <h3>🚀 Momentum & Benchmark</h3>
        <p><strong>${results.scorecard.momentumCategory.label}</strong></p>
        <p>${results.scorecard.momentumCategory.summary}</p>
        <br>
        <p><strong>${results.scorecard.benchmarkBand.label}</strong></p>
        <p>${results.scorecard.benchmarkBand.summary}</p>
      </div>

      <div class="section">
        <h3>💡 Key Strengths</h3>
        ${results.scorecard.strengths.map(s => `
          <div class="metric">
            <span>${s.title}</span>
            <span>${s.detail}</span>
          </div>
        `).join('')}
      </div>

      <div class="section">
        <h3>🎯 Top Opportunities</h3>
        ${results.scorecard.opportunities.slice(0, 3).map((opp, i) => `
          <div class="opportunity">
            <h4>${i + 1}. ${opp.title}</h4>
            <p>${opp.detail}</p>
            <p><strong>Action:</strong> ${opp.action}</p>
            <p><strong>Effort:</strong> ${opp.effort} | <strong>Timeframe:</strong> ${opp.timeframe}</p>
          </div>
        `).join('')}
      </div>

      <div style="text-align: center;">
        <a href="${reportUrl}" class="cta">🔗 View Full Report</a>
      </div>

      <div class="footer">
        <p>Generated by FlowIntent Reddit Gap Analysis</p>
        <p>AI-powered content strategy insights from Reddit discussions</p>
      </div>
    </body>
    </html>
  `

  return {
    to: input.email.trim().toLowerCase(),
    subject,
    text,
    html
  }
}

async function sendViaResend(payload: RedditGapEmailPayload): Promise<boolean> {
  const apiKey = process.env.RESEND_API_KEY
  const from = process.env.AUDIT_REPORT_FROM_EMAIL || 'noreply@flowintent.com'

  if (!apiKey) {
    console.warn('[Reddit Gap] RESEND_API_KEY not configured')
    return false
  }

  try {
    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from,
        to: payload.to,
        subject: payload.subject,
        text: payload.text,
        html: payload.html,
      }),
    })

    if (!response.ok) {
      const error = await response.text()
      throw new Error(`Resend API failed with ${response.status}: ${error}`)
    }

    console.log('[Reddit Gap] Email sent successfully via Resend')
    return true
  } catch (error) {
    console.error('[Reddit Gap] Failed to send email via Resend:', error)
    return false
  }
}

export async function sendRedditGapEmail(input: RedditGapEmailInput): Promise<boolean> {
  const payload = buildRedditGapEmailPayload(input)
  
  const sent = await sendViaResend(payload)
  if (!sent) {
    console.warn('[Reddit Gap] Email delivery failed (no provider configured)')
  }
  
  return sent
}
