/**
 * Chat Message Types
 * Supports both text and image messages in the chat interface
 */

export type MessageRole = 'user' | 'assistant' | 'system'

export type MessageType = 'text' | 'image'

/**
 * Base message properties shared by all message types
 */
export interface BaseMessage {
  id: string
  conversationId: string
  role: MessageRole
  createdAt: string
}

/**
 * Text message (standard chat message)
 */
export interface TextMessage extends BaseMessage {
  type: 'text'
  content: string
}

/**
 * Image message (generated by DALL-E 3)
 */
export interface ImageMessage extends BaseMessage {
  type: 'image'
  prompt: string
  content?: string  // For compatibility with message display
  revisedPrompt?: string
  size: '1024x1024' | '1792x1024' | '1024x1792'
  quality?: 'standard' | 'hd'
  style?: 'vivid' | 'natural'
  seed?: number
  model: 'dall-e-3' | 'google/gemini-2.5-flash-image'
  base64?: string
  imageBase64?: string  // Alternative field name for compatibility
  url?: string
  mediaType?: string
  providerMetadata?: any
  warnings?: any[]  // Can be string[] or warning objects
  status?: 'loading' | 'done' | 'error'
  errorMessage?: string
}


/**
 * Union type for all message types
 */
export type ChatMessage = TextMessage | ImageMessage

/**
 * Type guards for message types
 */
export function isTextMessage(message: ChatMessage): message is TextMessage {
  return message.type === 'text'
}

export function isImageMessage(message: ChatMessage): message is ImageMessage {
  return message.type === 'image'
}

/**
 * Image generation request parameters
 */
export interface ImageGenerationRequest {
  prompt?: string
  previousPrompt?: string
  editInstructions?: string
  size?: '1024x1024' | '1792x1024' | '1024x1792'
  quality?: 'standard' | 'hd'
  style?: 'vivid' | 'natural'
  seed?: number
  abortTimeoutMs?: number
  conversationId?: string
  parentMessageId?: string
}

/**
 * Image generation response
 */
export interface ImageGenerationResponse {
  base64: string
  prompt: string
  revisedPrompt?: string
  providerMetadata?: any
  warnings?: string[]
  size: string
  model: 'dall-e-3' | 'google/gemini-2.5-flash-image' | string
}


/**
 * Image mode preferences
 */
export interface ImageModePreferences {
  size: '1024x1024' | '1792x1024' | '1024x1792'
  quality: 'standard' | 'hd'
  style: 'vivid' | 'natural'
  seed?: number
}
