#!/usr/bin/env bash
# Bootstrap Geomode (Elmo) GEO tracking stack on a single-node Vultr VPS.
# Run as root after SSH access is restored.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/<org>/seobot/main/scripts/deploy/geomode-vultr-bootstrap.sh | bash
#   # or copy to the VPS and run:
#   chmod +x geomode-vultr-bootstrap.sh && ./geomode-vultr-bootstrap.sh
#
# Non-interactive (requires pre-set secrets — see docs/deployment/geomode-vultr.md):
#   ELMO_NONINTERACTIVE=1 BETTER_AUTH_SECRET=... OPENROUTER_API_KEY=... ./geomode-vultr-bootstrap.sh
#
# Prerequisites: Ubuntu 24.04/26.04, 2+ vCPU, 4+ GiB RAM, 40+ GiB disk.

set -euo pipefail

ELMO_DIR="${ELMO_DIR:-/opt/elmo}"
ELMO_CLI_VERSION="${ELMO_CLI_VERSION:-0.2.12}"
PUBLIC_APP_PORT="${PUBLIC_APP_PORT:-1515}"
GEOMODE_REPO="${GEOMODE_REPO:-https://github.com/sodown4thecause/geomode.git}"
GEOMODE_DIR="${GEOMODE_DIR:-/opt/geomode}"

log() { printf '[geomode-bootstrap] %s\n' "$*"; }
die() { printf '[geomode-bootstrap] ERROR: %s\n' "$*" >&2; exit 1; }

compose_cmd() {
  if docker compose version >/dev/null 2>&1; then
    echo "docker compose"
  elif command -v docker-compose >/dev/null 2>&1; then
    echo "docker-compose"
  else
    die "Neither 'docker compose' nor docker-compose found"
  fi
}

random_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  elif command -v dd >/dev/null 2>&1 && command -v xxd >/dev/null 2>&1; then
    dd if=/dev/urandom bs=32 count=1 2>/dev/null | xxd -p -c 64 | tr -d '\n'
  else
    die "Need openssl or dd+xxd to generate secrets"
  fi
}

write_noninteractive_env() {
  local env_file="${ELMO_DIR}/.env"
  local auth_secret="${BETTER_AUTH_SECRET:-$(random_secret)}"
  local db_password="${ELMO_POSTGRES_PASSWORD:-postgres}"

  mkdir -p "${ELMO_DIR}"
  cat >"${env_file}" <<EOF
# Generated by geomode-vultr-bootstrap.sh (non-interactive)
# Matches Elmo default Postgres service credentials (postgres user)
DATABASE_URL=postgresql://postgres:${db_password}@postgres:5432/elmo
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${db_password}
POSTGRES_DB=elmo
BETTER_AUTH_SECRET=${auth_secret}
PUBLIC_APP_PORT=${PUBLIC_APP_PORT}

# Provider keys — set at least one for useful captures
OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
DATAFORSEO_LOGIN=${DATAFORSEO_LOGIN:-}
DATAFORSEO_PASSWORD=${DATAFORSEO_PASSWORD:-}

# CloakBrowser targets (requires geomode fork provider)
SCRAPE_TARGETS=${SCRAPE_TARGETS:-chatgpt:openrouter:online,perplexity:openrouter:online}
EOF
  chmod 600 "${env_file}"
  log "Wrote ${env_file} (non-interactive template)"
}

if [[ "$(id -u)" -ne 0 ]]; then
  die "Run as root (or with sudo)."
fi

export DEBIAN_FRONTEND=noninteractive

log "Updating packages..."
apt-get update -y
apt-get upgrade -y

log "Installing Docker, Node.js, npm, jq..."
apt-get install -y \
  ca-certificates \
  curl \
  git \
  gnupg \
  jq \
  lsb-release \
  docker.io \
  docker-compose-v2 \
  npm

systemctl enable docker
systemctl start docker

COMPOSE="$(compose_cmd)"
log "Using compose command: ${COMPOSE}"

if ! command -v node >/dev/null 2>&1 || [[ "$(node -p 'process.versions.node.split(".")[0]')" -lt 20 ]]; then
  log "Installing Node.js 22 via NodeSource..."
  curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
  apt-get install -y nodejs
fi

log "Installing @elmohq/cli@${ELMO_CLI_VERSION}..."
npm install -g "@elmohq/cli@${ELMO_CLI_VERSION}"

mkdir -p "${ELMO_DIR}"
cd "${ELMO_DIR}"

if [[ ! -f "${ELMO_DIR}/.env" ]]; then
  if [[ "${ELMO_NONINTERACTIVE:-}" == "1" ]]; then
    write_noninteractive_env
    if [[ "${GEOMODE_USE_FORK:-}" == "1" ]]; then
      log "Cloning geomode fork for dev compose context..."
      if [[ ! -d "${GEOMODE_DIR}/.git" ]]; then
        git clone "${GEOMODE_REPO}" "${GEOMODE_DIR}"
      fi
      elmo --dir "${ELMO_DIR}" init --dev --docker-dir "${GEOMODE_DIR}" || die "elmo init --dev failed"
    else
      elmo --dir "${ELMO_DIR}" init --yes || die "elmo init --yes failed in non-interactive mode (check @elmohq/cli version and provider env vars)"
    fi
  else
    log "Running interactive elmo init in ${ELMO_DIR}..."
    log "Choose: Postgres in Docker, then Recommended or Custom providers."
    log "After init, credentials live in ${ELMO_DIR}/.env and ${ELMO_DIR}/elmo.yaml"
    elmo --dir "${ELMO_DIR}" init
  fi
else
  log "Found existing ${ELMO_DIR}/.env — skipping elmo init"
fi

log "Starting Elmo stack..."
elmo --dir "${ELMO_DIR}" compose up -d

log "Waiting for containers..."
sleep 10
elmo --dir "${ELMO_DIR}" compose ps
docker ps --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'

# Docker publishes container ports on 0.0.0.0 by default, which bypasses UFW
# because Docker manipulates the DOCKER chain directly in iptables/nftables.
# This VPS is tunnel-only (Cloudflare Tunnel) — no app port should be reachable
# from the public internet. UFW deny rules alone are insufficient; block external
# access at the DOCKER-USER chain so only loopback (and the tunnel) can reach the
# published port. See docs/specs/2026-06-12-geomode-geo-tracking-design.md
if command -v ufw >/dev/null 2>&1; then
  if ufw status 2>/dev/null | grep -qi 'Status: active'; then
    ufw deny "${PUBLIC_APP_PORT}/tcp" comment 'geomode tunnel-only' >/dev/null 2>&1 || true
    log "UFW: denied inbound TCP ${PUBLIC_APP_PORT} (access via Cloudflare Tunnel only)"
  else
    log "NOTE: Enable UFW or configure Cloudflare Tunnel before exposing this VPS publicly"
  fi
fi

if command -v iptables >/dev/null 2>&1; then
  if ! iptables -C DOCKER-USER -p tcp --dport "${PUBLIC_APP_PORT}" ! -i lo -j DROP >/dev/null 2>&1; then
    iptables -I DOCKER-USER -p tcp --dport "${PUBLIC_APP_PORT}" ! -i lo -j DROP
  fi
  log "iptables DOCKER-USER: dropped external TCP ${PUBLIC_APP_PORT} (tunnel-only, loopback allowed)"
fi

# Access is via Cloudflare Tunnel only — do NOT open the app port in UFW.
# See docs/specs/2026-06-12-geomode-geo-tracking-design.md

SERVER_IP="$(curl -fsS https://api.ipify.org 2>/dev/null || hostname -I | awk '{print $1}')"

cat <<EOF

================================================================================
Geomode / Elmo bootstrap complete
================================================================================
Config directory : ${ELMO_DIR}
Web UI (local)   : http://127.0.0.1:${PUBLIC_APP_PORT}
Server IP        : ${SERVER_IP} (app port intentionally NOT exposed publicly)

Credentials      : ${ELMO_DIR}/.env
Compose file     : ${ELMO_DIR}/elmo.yaml (or docker-compose.yml — check ${ELMO_DIR})

Useful commands:
  elmo --dir ${ELMO_DIR} compose ps
  elmo --dir ${ELMO_DIR} compose logs -f
  elmo --dir ${ELMO_DIR} compose down

Next step: install cloudflared and route geo.<your-domain> -> http://127.0.0.1:${PUBLIC_APP_PORT}
(see docs/specs/2026-06-12-geomode-geo-tracking-design.md — VPS bring-up section)

FlowIntent env (Vercel) — set AFTER the tunnel is up:
  ELMO_API_URL=https://geo.<your-domain>
  ELMO_API_KEY=<from ${ELMO_DIR}/.env ADMIN_API_KEYS after geomode is deployed>

Tear-down backup (before destroying VPS):
  elmo --dir ${ELMO_DIR} compose exec -T postgres pg_dumpall -U postgres > /root/elmo-pg-backup.sql
  tar -czf /root/elmo-config-backup.tgz -C ${ELMO_DIR} .env elmo.yaml docker-compose.yml 2>/dev/null || true
================================================================================
EOF
